### ISSUE TITLE
Desarrollar ADR 3: NodeJS

### ISSUE THREAD

**Issue by uo284373** [Arquisoft/lomap_es3a#112]
# Tarea
Se debe desarrollar el documento de Decisión Arquitectónica sobre NodeJS
- [x] ADR NodeJS

**Comment by Omitg24** [comment]
Ya he realizaco la ADR3.
Puedes acceder a través del siguiente <a href="https://github.com/Arquisoft/lomap_es3a/wiki/(ADR3)-NodeJS">enlace</a>.
