### ISSUE TITLE
[E2] - AutoInforme de David Warzynski (UO278968)

### ISSUE THREAD

**Issue by UO278968** [Arquisoft/lomap_es3a#136]
# AutoInforme - Segundo Entregable

<p align="center">
<img src="https://user-images.githubusercontent.com/91057639/218811134-2eec75dc-a6d5-42f7-b1d6-fae6bd5ac158.png" width="640" height="320">
</p>

## 👨‍🎓 Datos del desarrollador:
<ul>
      <li><strong>Nombre:</strong> <em>David</em>.</li>
      <li><strong>Apellidos:</strong> <em>Warzynski</em>.</li>
      <li><strong>UO:</strong> <em>UO278968</em>.</li>
      <li><strong>Correo electrónico:</strong> <a href="mailto:UO278968@uniovi.es"><em>UO278968@uniovi.es</em></a>.</li>
</ul>

### Descripción general:
<p align="justify">
A lo largo de estas semanas he realizado diversas tareas para el equipo, además de participar en el desarrollo de las actas (tanto presenciales como telemáticas).
</p>
<p align="justify">
He participado en la búsqueda de información en conjunto con mis compañeros, buscando documentación sobre el uso de las tecnologías asignadas (React, SOLID), así como el uso de las librerías usadas para la aplicación como Bootstrap, mui/material, Leaftlet .
</p>
</p>
<p align="justify">
He corregido las tareas referentes a las mejoras que se nos pidieron en la revisión anterior sobre la documentación, corrigiendo los diagramas de nivel 1 y 2 usando flechas discontinuas para representar el intercambio de datos con el POD, además se ha corregido las palabras usadas para referirnos al incidente ocurrido con el miembro que tuvo que abandonar el grupo para equilibrar los equipos.
</p>
<p align="justify">
Con respecto a la aplicación, he sido el responsable de implementar al login así como la recuperación de datos del usuario de su POD para mostrar la información del usuario autenticado en el proveedor de Inrupt.
</p>

### Número de _issues_ realizadas:
Se han realizado ***8*** issues en el momento de redacción del informe.

### 🔗 Enlaces a _issues_:
<ol type="1">
       <li>#70.</li>
       <li>#72.</li>
       <li>#76.</li>
       <li>#77.</li>
       <li>#78.</li>
       <li>#100.</li>
       <li>#102.</li>
       <li>#106.</li>
</ol>

## ✅ Aprobación de los miembros restantes del equipo:
- [x] Carlos Diez Fernández, [UO284373](mailto:UO284373@uniovi.es)
- [x] Omar Teixeira González, [UO281847](mailto:UO281847@uniovi.es)
- [x] Raúl Fernández España, [UO278036](mailto:UO278036@uniovi.es)

**Comment by Omitg24** [comment]
Buen trabajo David!

**Comment by UO278036** [comment]
Buen trabajo David, me gusta mucho el Login!

**Comment by uo284373** [comment]
Gran trabajo David. A seguir así.
