### ISSUE TITLE
[E2] - AutoInforme de Carlos Diez Fernández (UO284373)

### ISSUE THREAD

**Issue by uo284373** [Arquisoft/lomap_es3a#139]
# AutoInforme - Segundo Entregable

<p align="center">
<img src="https://user-images.githubusercontent.com/91057639/218811134-2eec75dc-a6d5-42f7-b1d6-fae6bd5ac158.png" width="640" height="320">
</p>

## 👨‍🎓 Datos del desarrollador:
<ul>
      <li><strong>Nombre:</strong> <em>Carlos</em>.</li>
      <li><strong>Apellidos:</strong> <em>Diez Fernández</em>.</li>
      <li><strong>UO:</strong> <em>284373</em>.</li>
      <li><strong>Correo electrónico:</strong> <a href="uo284373:@uniovi.es"><em>uo284373@uniovi.es</em></a>.</li>
</ul>

### Descripción general:
<p align="justify">
A lo largo de estas semanas he realizado diversas tareas para el equipo, además de participar en el desarrollo de las actas (tanto presenciales como telemáticas).
Para empezar he desarrollado una versión inicial con un nav y el mapa que sirvió como base para desarrollar el resto de la aplicación.
Por otro lado, en la página de home he desarrollado el footer que incluye los botones con los enlaces a las diferentes tecnologías que hemos utilizado en este proyecto.
Además, en la página del mapa incorporé el mapa utilizando como proveedor de mapas OpenStreetMaps. 
También, añadí la funcionalidad de que aparezca un menú para añadir marcadores cada vez que el usuario hace click sobre un punto de mapa. En este menú el usuario puede añadir el nombre del lugar, un comentario, la categoría del lugar y la puntuación. Por último hay un botón para añadir marcador al POD del usuario.
Sobre este último punto, he investigado y he desarrollado la funcionalidad para que al pulsar este botón se genere un archivo json con la información introducida por el usuario y lo guarde en la carpeta public del POD del usuario. Para ello se ha utilizado la función saveFileInContainer de @inrupt/solid-client.
Por último, comentar que he ayudado a los compañeros a realizar alguna de sus funciones y he participado en todas las reuniones presenciales y telemáticas, redactando varias de las actas.
</p>
### Número de _issues_ realizadas:
Se han realizado ***14*** issues en el momento de redacción del informe.

### 🔗 Enlaces a _issues_:
<ol type="1">
       <li>#106.</li> 
       <li>#95.</li> 
       <li>#100.</li> 
       <li>#98.</li> 
       <li>#126.</li> 
       <li>#99.</li> 
       <li>#78.</li> 
       <li>#103.</li> 
       <li>#77.</li> 
       <li>#91.</li> 
       <li>#55.</li> 
       <li>#84.</li> 
       <li>#76.</li> 
       <li>#63.</li> 
</ol>

## ✅ Aprobación de los miembros restantes del equipo:
- [x] Raúl Fernández España, [UO278036](mailto:UO278036@uniovi.es)
- [x] Omar Teixeira González, [UO281847](mailto:UO281847@uniovi.es)
- [x] David Leszek Warzynski Abril, [UO278968](mailto:UO278968@uniovi.es)

**Comment by Omitg24** [comment]
Muy buen trabajo Carlos

**Comment by UO278968** [comment]
Gran trabajo con el guardado de información en el POD

**Comment by UO278036** [comment]
Muy buen trabajo, me gustan mucho los marcadores
