### ISSUE TITLE
Redacción de Documentación: #8 Conceptos Transversales (Cross-cutting)

### ISSUE THREAD

**Issue by Omitg24** [Arquisoft/lomap_es3a#16]
# Tarea
Redactar el documento: 08_concepts.adoc
- [x] Domain model
- [x] Security
- [x] Testability

**Comment by Omitg24** [comment]
# Ayuda
Necesito ayuda con la generación del modelo de dominio, al menos para comprobar que está bien realizado.

Muchas gracias,
Omar.

**Comment by uo284373** [comment]
Hola Omar, te he dejado un comentario en la _discussion_  creada sobre este tema.

De nada.
Carlos
