### ISSUE TITLE
[E3] - AutoInforme de David Warzynski Abril (UO278968)

### ISSUE THREAD

**Issue by UO278968** [Arquisoft/lomap_es3a#277]
# AutoInforme - Tercer Entregable

<p align="center">
<img src="https://user-images.githubusercontent.com/91057639/218811134-2eec75dc-a6d5-42f7-b1d6-fae6bd5ac158.png" width="640" height="320">
</p>

## 👨‍🎓 Datos del desarrollador:
<ul>
      <li><strong>Nombre:</strong> <em>David</em>.</li>
      <li><strong>Apellidos:</strong> <em>Warzynski</em>.</li>
      <li><strong>UO:</strong> <em>UO278968</em>.</li>
      <li><strong>Correo electrónico:</strong> <a href="mailto:UO278968@uniovi.es"><em>UO278968@uniovi.es</em></a>.</li>
</ul>

### Descripción general:
<p align="justify">
He realizado una investigación sobre la generación de los test correspondientes a la aplicación para cubrir las lineas de código del proyecto para poder pasar los test apropiados, se ha creado un único fichero en el POD para almacenar los marcadores del usuario y poder cargarlos posteriormente en el mapa, se ha corregido la correcta actualización del mapa después de crear un marcador, además se ha creado un filtro de categorías en el mapa para visualizar los marcadores del usuario, también se ha buscado iconos para relacionar las categorías de los marcadores con un referencia visual en el mapa.
</p>

### Número de _issues_ realizadas:
Se han realizado ***7*** issues en el momento de redacción del informe.

### 🔗 Enlaces a _issues_:
<ol type="1">
       <li>#156.</li> 
       <li>#200.</li>
       <li>#203.</li>
       <li>#204.</li> 
       <li>#266.</li> 
       <li>#268.</li> 
       <li>#269.</li> 
</ol>

## ✅ Aprobación de los miembros restantes del equipo:
- [x] Carlos Diez Fernández, [UO284373](mailto:UO284373@uniovi.es)
- [x] Omar Teixeira González, [UO281847](mailto:UO281847@uniovi.es)
- [x] Raúl Fernández España, [UO278036](mailto:UO278036@uniovi.es)

**Comment by UO278036** [comment]
Muy bien, sigue asi!

**Comment by uo284373** [comment]
Grandes avances en el back-end. El equipo back-end manda

**Comment by Omitg24** [comment]
Muy buen trabajo mi estimado señor Warzynski, tras multiples discusiones, hemos llegado a un acuerdo del front-end.... Espero que ahora le guste más, sino... Pues a cambiarlo otra vez.
