### ISSUE TITLE
[E3] - AutoInforme de Carlos Diez Fernández(UO284373)

### ISSUE THREAD

**Issue by uo284373** [Arquisoft/lomap_es3a#278]
# AutoInforme - Tercer Entregable

<p align="center">
<img src="https://user-images.githubusercontent.com/91057639/218811134-2eec75dc-a6d5-42f7-b1d6-fae6bd5ac158.png" width="640" height="320">
</p>

## 👨‍🎓 Datos del desarrollador:
<ul>
      <li><strong>Nombre:</strong> <em>Carlos</em>.</li>
      <li><strong>Apellidos:</strong> <em>Diez Fernández</em>.</li>
      <li><strong>UO:</strong> <em>284373</em>.</li>
      <li><strong>Correo electrónico:</strong> <a href="uo284373:@uniovi.es"><em>uo284373@uniovi.es</em></a>.</li>
</ul>

### Descripción general:
<p align="justify">
A lo largo de estas semanas he realizado diversas tareas para el equipo, además de participar en el desarrollo de las actas (tanto presenciales como telemáticas).
Principalmente, he desarrollado dos tareas relacionadas con el backend. En primer lugar, he realizado la funcionalidad que permite mostrar todos los marcadores del usuario que tiene iniciada sesión. Es decir, cuando el usuario inicie sesión se le mostrará el mapa con todos los marcadores que tiene guardados en su POD. Además, he realizado la funcionalidad para que al añadir un marcador al mapa, directamente se actualice el mapa y aparezca.
La segunda funcionalidad que he realizado se basa en añadir al menú de opciones una lista formado por los amigos que tiene añadido el usuario. Esta lista está formada por un botón por cada amigo que tenga el usuario de forma que al darle se cambian los permisos de la carpeta private para que tus amigos puedan tener acceso a tus marcadores.
Finalmente, modifiqué la funcionalidad de añadir marcadores al POD para que añadiera las coordenadas del punto al POD, así como modifique el panel lateral derecho para que al añadir el marcador se muestren las coordenadas del punto a añadir.
Por último, comentar que he ayudado a los compañeros a realizar alguna de sus funciones y he participado en todas las reuniones presenciales y telemáticas, redactando varias de las actas.
</p>

### Número de _issues_ realizadas:
Se han realizado ***9*** issues en el momento de redacción del informe.

### 🔗 Enlaces a _issues_:
<ol type="1">
       <li>#150.</li> 
       <li>#155.</li> 
       <li>#158.</li> 
       <li>#162.</li> 
       <li>#185.</li> 
       <li>#200.</li> 
       <li>#232.</li> 
       <li>#263.</li> 
       <li>#266.</li> 
</ol>

## ✅ Aprobación de los miembros restantes del equipo:
- [x] Raúl Fernández España, [UO278036](mailto:UO278036@uniovi.es)
- [x] Omar Teixeira González, [UO281847](mailto:UO281847@uniovi.es)
- [x] David Leszek Warzynski Abril, [UO278968](mailto:UO278968@uniovi.es)

**Comment by UO278968** [comment]
Back-end glorioso sigue así, estas dominando los PODs. 😸 :

**Comment by UO278036** [comment]
Muy buen trabajo!

**Comment by Omitg24** [comment]
Gran trabajo Carlos, estoy orgulloso de tu progreso con los PODs!
