### ISSUE TITLE
[E4] - AutoInforme de David Warzynski Abril (UO278968)

### ISSUE THREAD

**Issue by UO278968** [Arquisoft/lomap_es3a#445]
# AutoInforme - Cuarto entregable

<p align="center">
<img src="https://user-images.githubusercontent.com/91057639/218811134-2eec75dc-a6d5-42f7-b1d6-fae6bd5ac158.png" width="640" height="320">
</p>

## 👨‍🎓 Datos del desarrollador:
<ul>
      <li><strong>Nombre:</strong> <em>David</em>.</li>
      <li><strong>Apellidos:</strong> <em>Warzynski</em>.</li>
      <li><strong>UO:</strong> <em>UO278968</em>.</li>
      <li><strong>Correo electrónico:</strong> <a href="mailto:UO278968@uniovi.es"><em>UO278968@uniovi.es</em></a>.</li>
</ul>

### Descripción general:
<p align="justify">
 He realizado la publicación de reviews e imagenes en marcadores creados con aterioridad en el POD de los amigos o los propios, además se añadieron nuevas categorias a las anteriores para poder corresponder con las que estan especificadas en el repositorio de lomapSpec, se han corregido diversos bugs de visualización de los datos de los marcadores. Por último se ha corregido el formato de los datos.
</p>

### Número de _issues_ realizadas:
Se han realizado ***13*** issues en el momento de redacción del informe.

### 🔗 Enlaces a _issues_:
<ol type="1">
       <li>#414.</li> 
       <li>#413.</li>
<li>#354.</li>  
<li>#345.</li>
<li>#344.</li>  
<li>#326.</li> 
<li>#325.</li>
<li>#309.</li>
<li>#308.</li>  
<li>#307.</li>
<li>#306.</li> 
<li>#301.</li>
<li>#300.</li>
</ol>

## ✅ Aprobación de los miembros restantes del equipo:
- [x] Carlos Diez Fernández, [UO284373](mailto:UO284373@uniovi.es)
- [x] Omar Teixeira González, [UO281847](mailto:UO281847@uniovi.es)
- [x] Raúl Fernández España, [UO278036](mailto:UO278036@uniovi.es)

**Comment by UO278036** [comment]
Muy buen trabajo David!
