### ISSUE TITLE
Crear kanban para la administración de tareas del proyecto

### ISSUE THREAD

**Issue by UO278036** [Arquisoft/lomap_es3a#6]
Necesidad de crear el Kanban para poder administrar las diferentes tareas a realizar entre los miembros del proyecto

**Comment by Omitg24** [comment]
Ya he creado el proyecto de, he seguido una plantilla que parece que se pude adaptar correctamente a nuestras necesidades durante el desarrollo del proyecto.
Se puede acceder a través de la pestaña Projects, o a través del siguiente [enlace](https://github.com/orgs/Arquisoft/projects/24)
