### ISSUE TITLE
[E1] - Autoinforme de Carlos Diez Fernández (UO284373)

### ISSUE THREAD

**Issue by uo284373** [Arquisoft/lomap_es3a#60]
# AutoInforme - Primer Entregable

<p align="center">
<img src="https://user-images.githubusercontent.com/91057639/218811134-2eec75dc-a6d5-42f7-b1d6-fae6bd5ac158.png" width="640" height="320">
</p>

## 👨‍🎓 Datos del desarrollador:
<ul>
      <li><strong>Nombre:</strong> <em>Carlos</em>.</li>
      <li><strong>Apellidos:</strong> <em>Diez Fernández</em>.</li>
      <li><strong>UO:</strong> <em>UO284373</em>.</li>
      <li><strong>Correo electrónico:</strong> <a href="mailto:UO284373@uniovi.es"><em>UO284373@uniovi.es</em></a>.</li>
</ul>

### Descripción general:
<p align="justify">
A lo largo de estas semanas he realizado diversas funciones, principalmente enfocadas en realizar la documentación y ayudar a los miembros del equipo, respondiendo las respectivas dudas planteadas.
</p>

<p align="justify">
Además, he participado en todas las reuniones tanto presenciales como telemáticas, en las que se ha distribuido el trabajo a realizar y hemos resuelto las dudas que se han planteado. A su vez, he redactado varias actas de las reuniones mencionadas.
</p>

<p align="justify">
Con respecto a lo que trata la entrega en si, la documentación, he participado en la redacción de los documentos 1, 2, 3 y 4 y me he encargado de redactar yo solo el documento 7.
</p>

<p align="justify">
Otra de las partes que en las que he participado ha sido a la hora de obtener y recopilar información sobre la tecnología SOLID, que se va a seguir en el proyecto, siguiendo los principios que esta tecnología define.
</p>

<p align="justify">
Otra de las partes en las que he participado ha sido ayudando a los miembros del equipo, respondiendo las distintas dudas que han planteado en las siguientes Discussions:
</p>
<ul>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/42">Canal general del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/35">Canal de diseños del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/36">Canal de funciones del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/37">Canal de documentación del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/39">Canal de pruebas del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/40">Canal de anuncios del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/41">Canal de preguntas sobre el proyecto</a>.</li>
</ul>

### Número de _issues_ realizadas:
Se han realizado ***6*** issues en el momento de redacción del informe.

### 🔗 Enlaces a _issues_:
<ol type="1">
       <li>#4.</li> 
       <li>#10.</li>
       <li>#11.</li>
       <li>#12.</li>
       <li>#13.</li>
       <li>#15.</li>
</ol>

## ✅ Aprobación de los miembros restantes del equipo:
- [x] Raúl Fernández España, [UO278036](mailto:UO278036@uniovi.es)
- [x] David Leszek Warzynski Abril, [UO278968](mailto:UO278968@uniovi.es)
- [x] Omar Teixeira González, [UO281847](mailto:UO281847@uniovi.es)

**Comment by Omitg24** [comment]
Muy buen trabajo Carlos!

**Comment by UO278968** [comment]
Gran trabajo Carlos !!!

**Comment by UO278036** [comment]
Buen trabajo Carlos!
