### ISSUE TITLE
[E1] - AutoInforme de David Warzynski (UO278968) 

### ISSUE THREAD

**Issue by UO278968** [Arquisoft/lomap_es3a#61]
# AutoInforme - Primer Entregable

<p align="center">
<img src="https://user-images.githubusercontent.com/91057639/218811134-2eec75dc-a6d5-42f7-b1d6-fae6bd5ac158.png" width="640" height="320">
</p>

## 👨‍🎓 Datos del desarrollador:
<ul>
      <li><strong>Nombre:</strong> <em>David</em>.</li>
      <li><strong>Apellidos:</strong> <em>Warzynski Abril</em>.</li>
      <li><strong>UO:</strong> <em>UO278968</em>.</li>
      <li><strong>Correo electrónico:</strong> <a href="mailto:UO278968@uniovi.es"><em>UO278968@uniovi.es</em></a>.</li>
</ul>

### Descripción general:
<p align="justify">
Durante el desarrollo de estas primeras semanas mi función ha sido dirigida al desarrollo de la documentación. Para ello he creado una carpeta compartida usando OneDrive con las plantillas de las diferentes secciones de la misma para favorecer la realización simultanea de los documentos junto al resto de integrantes.
</p>

<p align="justify">
He participado en las distintas reuniones realizadas tanto en clase de practicas de forma presencial, como reuniones telemáticas donde se discutía que trabajo había que realizar y como repartirlo. Por otra parte, también me he encargado de redactar el Acta 2 de la sesión presencial.
</p>

<p align="justify">
Con respecto a la documentación, he participado en la redacción de los documentos 1, 2, 3, 4, 5 además el documento 6 con los diagramas de secuencia usando plantUML para su realización, habiendo realizado la labor de investigación de dicha herramienta con anterioridad.  
</p>

<p align="justify">
Otra de las partes que en las que he participado ha sido a la hora de obtener y recopilar información sobre la tecnología de base de datos que vamos a usar para el desarrollo del proyecto (MongoDB) con el fin de agilizar el mismo.
</p>

<p align="justify">
Otra de las partes en las que he participado ha sido ayudando a los miembros del equipo, respondiendo las distintas dudas que han planteado en las siguientes Discussions:
</p>
<ul>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/42">Canal general del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/35">Canal de diseños del proyecto</a>.</li>
       <li><a href="https://github.com/Arquisoft/lomap_es3a/discussions/41">Canal de preguntas sobre el proyecto</a>.</li>
</ul>

### Número de _issues_ realizadas:
Se han realizado ***6*** issues en el momento de redacción del informe.

### 🔗 Enlaces a _issues_:
<ol type="1">
       <li>#4.</li> 
       <li>#10.</li>
       <li>#11.</li>
       <li>#12.</li>
       <li>#13.</li>
       <li>#14.</li>
</ol>

## ✅ Aprobación de los miembros restantes del equipo:
- [x] Raúl Fernández España, [UO278036](mailto:UO278036@uniovi.es)
- [x] Carlos Diez Fernández, [UO284373](mailto:UO284373@uniovi.es)
- [x] Omar Teixeira González, [UO281847](mailto:UO281847@uniovi.es)

**Comment by uo284373** [comment]
Muy buen trabajo, David!

**Comment by Omitg24** [comment]
Gran trabajo David! A seguir así.

**Comment by UO278036** [comment]
Excelente trabajo David! Muy buen desempeño!
